version: "3"

services:
  postgesql:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=nodedb
    networks: 
      - server_network

networks:
  server_network:
    driver: bridge
